name: heavyai-olio
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.8

  - pytest

  - pandas

  - pyarrow

  # heavyai libraries
  - heavyai
  - ibis-heavyai = 1.1
  - sqlalchemy-heavyai

  # geo
  - geopandas = 0.9
  - geos = 3.9.1
  - shapely = 1.7.1
  - pygeos = 0.10
  - gdal = 3.3.2
  # - gdal = 3.4.0

  - prefect = 2.2.0
  # - prefect = 0.15.13
  - dask-core = 2022.1.1
  - distributed = 2022.1.1

  - ipython
  - python-dotenv = 0.19
  - sqlparse = 0.4.2
